version: "3.2"

services:

  proxy:
    build:
      context: ./dockerfiles/nginx-proxy
      dockerfile: Dockerfile
    entrypoint:
      - tail
      - -f
      - /dev/null
    image: nginx-proxy
    container_name: nginx-proxy
    networks:
      - private-network
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./logs:/root/logs
      - ./src/spring/:/var/www/localhost/src/
  
  webapp:
    build:
      context: ./dockerfiles/php-composer
      dockerfile: Dockerfile
    entrypoint:
      - tail
      - -f
      - /dev/null
    image: php-composer:7.1.4
    container_name: php-composer
    networks:
      - private-network
    ports:
      - "9001:9000"
    environment:
      - TZ=Asia/Tokyo
    volumes:
     - ./src/laravel/:/var/www/html/webapp/
     - ./logs/php-composer/PHP_Laravel.log:/var/log/laravel.log
     - ./logs/php-composer/PHP_Access.log:/var/log/httpd/access_log
     - ./logs/php-composer/PHP_Error.log:/var/log/httpd/error_log
     - ./logs/php-composer/PHP_npm_compile.log:/var/log/npm_compile.log
  
  javaapp:
    build:
      context: ./dockerfiles/java-tomcat
      dockerfile: Dockerfile
    entrypoint:
      - tail
      - -f
      - /dev/null
    image: java-tomcat
    container_name: java-tomcat
    networks:
      - private-network
    ports:
      - "9002:9000"
    environment:
      - TZ=Asia/Tokyo
    volumes:
     - ./src/spring/:/opt/src/
     - ./logs/java-tomcat/Java_build.log:/var/log/build.log
     - ./logs/java-tomcat/Java_app.log:/var/log/javaapp.log

networks:
  private-network:
    driver: bridge