version: "3.2"

services:

  webapp:
    build:
      context: ../dockers/php-composer
      dockerfile: Dockerfile
    entrypoint:
      - tail
      - -f
      - /dev/null
    depends_on:
      - javaapp
    image: php-composer
    container_name: php-composer
    ports:
      - "80:80"
      - "9001:9000"
      - "8881:8881"
    environment:
      - TZ=Asia/Tokyo
    links:
      - javaapp
#    volumes:
#     - .:/code
  javaapp:
    build:
      context: ../dockers/java-tomcat
      dockerfile: Dockerfile
    entrypoint:
      - tail
      - -f
      - /dev/null
    image: java-tomcat
    container_name: java-tomcat
    ports:
      - "8080:8080"
      - "9002:9000"
      - "8882:8882"
    environment:
      - TZ=Asia/Tokyo
#    volumes:
#     - .:/opt/
