spring.datasource:
  url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
  driverClassName: org.h2.Driver
  username: sa
  password:
  h2.console.enabled: true
flyway.schemas: PUBLIC

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type:
        descriptor.sql.BasicBinder: TRACE